# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappos', '0002_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='rentals',
            field=models.ManyToManyField(to='zappos.User'),
        ),
    ]
