# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zappos', '0003_shoe_rentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='zappos.Shoe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='zappos.User')),
            ],
        ),
    ]
